pipeline{
  agent { label 'nodejs' }
  stages{
    stage ('checkout'){
      steps{
        checkout scm
      }
    }
    stage ('install modules'){
      steps{
        sh '''
          npm install --verbose -d 
          npm install --save classlist.js
        '''
      }
    }
    stage ('test'){
      steps{
       // sh '''
        //  $(npm bin)/ng test --single-run --browsers Chrome_no_sandbox
       /// '''
       sh '''
          echo 'Test stage'
        '''
      }
      post {
          always {
            //junit "test-results.xml"
          echo 'Test stage passed'
        
          }
      }
    }
    stage ('code quality'){
      steps{
        //sh '$(npm bin)/ng lint'
        echo 'linting'
      }
    }
    stage ('build') {
      steps{
        openshiftBuild(namespace: 'angular-5-example', bldCfg: 'angular-example-pipeline', showBuildLogs: 'true')
      }
    }
    stage ('build image') {
      steps{
        openshiftDeploy(namespace: 'angular-5-example', depCfg: 'angular-5-example')
      }
    }
  }
}
