pipeline{
  agent { label 'nodejs8' }
  stages{
    stage ('checkout'){
      steps{
        checkout scm
      }
    }
    stage ('install modules'){
      steps{
        sh '''
          npm install --verbose -d 
          npm install --save classlist.js
        '''
      }
    }
    stage ('test'){
      steps{
       // sh '''
        //  $(npm bin)/ng test --single-run --browsers Chrome_no_sandbox
       /// '''
       sh '''
          echo 'Test stage'
        '''
      }
      post {
          always {
            //junit "test-results.xml"
          echo 'Test stage passed'
        
          }
      }
    }
    stage ('code quality'){
      steps{
        //sh '$(npm bin)/ng lint'
        echo 'linting'
      }
    }
    stage ('build') {
      steps{
        sh '$(npm bin)/ng build --prod --build-optimizer'
      }
    }
    stage ('build image') {
      steps{
        sh '''
          rm -rf node_modules
          oc start-build test-project-angular-example-pipeline --from-dir=. --follow
        '''
      }
    }
  }
}
