kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "angular-example-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/arvindsinghsopra/angular-5-example"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node(''){
          stage 'Build using your-yourconfig'
              openshiftBuild(namespace: 'angular-5-example', bldCfg: 'angular-example-pipeline', showBuildLogs: 'true')
          stage 'Deployment using your-deploymentconfig'
              openshiftDeploy(namespace: 'angular-5-example', depCfg: 'angular-5-example')
      jenkinsfilePath: jenkins/Jenkinsfile
